name: holgerstorm
favicon: null
layout_spectrum: 0.55469
typography_spectrum: 0.80587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050b07'
    - '#006687'
    - '#5292c0'
    - '#86b4d6'
    - '#96887d'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
