name: holgerstorm
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.08297873
color:
  saturation: 0.4829787
  brandStrength: 1
  rhythmicContrast: 0.287234
  brandColors:
    - '#ebeffa'
    - '#cfc2c9'
    - '#2d414a'
    - '#66737c'
    - '#aa9b9e'
  lightness: 0.8212766
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
typography_spectrum: 0.8638298
