name: holgerstorm
favicon: null
layout_spectrum: 0.55469
typography_spectrum: 0.80587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebeffa'
    - '#cfc2c9'
    - '#2d414a'
    - '#66737c'
    - '#aa9b9e'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
